version: "3.1"
services:

  mysql:
    image: mysql:8.0
    container_name: symfony-rabbit-example-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    ports:
      - "10001:3306"

  webserver:
    image: nginx:alpine
    container_name: symfony-rabbit-example-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: docker/php-fpm
    container_name: symfony-rabbit-example-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  rabbit:
    container_name: symfony-rabbit-example-rabbit
    hostname: rabbit
    image: rabbitmq:3.8.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"